package ae.com.sun.xml.bind.v2.model.annotation;

import java.lang.annotation.Annotation;

import ae.javax.xml.bind.annotation.XmlNs;
import ae.javax.xml.bind.annotation.XmlNsForm;
import ae.javax.xml.bind.annotation.XmlSchema;

public class XmlSchemaMine implements XmlSchema
{

	public XmlSchemaMine(String namespace) {
		this.namespace = namespace;
	}
	
	@Override
	public Class<? extends Annotation> annotationType() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
    /**
     * Customize the namespace URI, prefix associations. By default,
     * the namespace prefixes for a XML namespace are generated by a
     * JAXB Provider in an implementation dependent way.
     */
	public XmlNs[] xmlns() {
		// TODO Auto-generated method stub
		return null;
	}

	private String namespace;
	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}
	
	@Override
	public String namespace() {
		return namespace;
	}

	@Override
	public XmlNsForm elementFormDefault() {
		return XmlNsForm.QUALIFIED;
	}

	@Override
	public XmlNsForm attributeFormDefault() {
		return XmlNsForm.UNSET;
	}

	@Override
	public String location() {
		// TODO Auto-generated method stub
		return null;
	}

}
